# Generated by Django 4.1.1 on 2022-09-11 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipotrabajo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Trabajos',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo_name', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrabajoMunicipio', to='system.municipio')),
                ('tipo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrabajoTipoTrabajo', to='system.tipotrabajo')),
            ],
            options={
                'verbose_name_plural': 'Centro de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(help_text='Carne de Identidad', max_length=11)),
                ('sexo', models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=1, null=True)),
                ('quota', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('municipio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileMunicipio', to='system.municipio')),
                ('trabajo', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='municipio', chained_model_field='municipio', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.trabajo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datos de administracion',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('msg_type', models.CharField(choices=[('1', 'Login'), ('2', 'Logout'), ('3', 'Error'), ('4', 'Desactivada'), ('100', 'Cuenta Creada'), ('101', 'Cuenta Borrada'), ('102', 'Cuenta Modificada'), ('103', 'Cuenta Desactivada'), ('104', 'Cuenta Recuperada'), ('105', 'Cambio Password'), ('106', 'Traslado de cuenta')], max_length=3)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
