# Generated by Django 4.1.1 on 2022-10-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='Alias del enlace')),
                ('ipwan', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='Bloque IP WAN')),
                ('ipwan_netmask', models.CharField(choices=[('/30', '/30'), ('/32', '/32')], max_length=3, verbose_name='Mascara')),
                ('iplan', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='Bloque IP LAN')),
                ('iplan_netmask', models.CharField(blank=True, choices=[('/24', '/24'), ('/25', '/25'), ('/26', '/26'), ('/27', '/27'), ('/28', '/28'), ('/29', '/29'), ('/30', '/30')], max_length=3, null=True, verbose_name='Mascara')),
                ('ed', models.CharField(max_length=100, verbose_name='ED')),
                ('ab', models.CharField(max_length=50, verbose_name='Ancho de Banda')),
                ('um_ab', models.CharField(choices=[('Kbps', 'Kbps'), ('Mbps', 'Mbps'), ('Gbps', 'Gbps')], max_length=4)),
                ('tipo_conexion', models.CharField(choices=[('adsl', 'ADSL'), ('fibra', 'Fibra Optica')], max_length=5, verbose_name='Tipo de conexión')),
                ('enrutamiento', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.municipio')),
                ('trabajo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.trabajo')),
            ],
            options={
                'verbose_name_plural': 'Enlaces dedicados',
            },
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizo', models.DateField(default=None, null=True)),
                ('cuota', models.CharField(max_length=6, null=True, verbose_name='Cuota de Internet (MB)')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP con Internet')),
                ('adsl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='InternetAdsl', to='adsl.enlace')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.municipio')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.trabajo')),
            ],
            options={
                'verbose_name_plural': 'Servicio Internet',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('msg_type', models.CharField(choices=[('200', 'Creado'), ('201', 'Traslado'), ('202', 'Cambio de IP'), ('203', 'Cambio de AB'), ('204', 'Internet Asignado'), ('205', 'Cambio de tecnologia'), ('206', 'Cambio de IP de Internet'), ('207', 'Enrutado')], max_length=3)),
                ('enlace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnlaceHistory', to='adsl.enlace')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
