# Generated by Django 4.1.1 on 2022-09-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Ocupacion',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('service_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(db_index=True, help_text='Carne de Identidad', max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('quota', models.IntegerField(help_text='Numero en Mb')),
                ('telefono', models.CharField(max_length=11)),
                ('telefono_work', models.CharField(max_length=11)),
                ('tipo_cuenta', models.CharField(choices=[('Personal', 'Personal'), ('Institucional', 'Intitusional')], max_length=13)),
                ('notas', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('expire_date', models.DateField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('mark_delete', models.BooleanField(default=False)),
                ('uidNumber', models.IntegerField(blank=True, null=True)),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersMunicipio', to='system.municipio')),
                ('ocupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersOcupacion', to='usuarios.ocupacion')),
                ('sldservice', models.ManyToManyField(related_name='UsersService', to='usuarios.services')),
                ('trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersTrabajo', to='system.trabajo')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('type_device', models.CharField(choices=[('1', 'Laptop'), ('2', 'Tablet'), ('3', 'Movil')], max_length=1)),
                ('mac_address', models.CharField(max_length=100)),
                ('os', models.CharField(choices=[('1', 'Windows'), ('2', 'iOS'), ('3', 'Android'), ('4', 'Linux'), ('5', 'Mac OXS')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceUsers', to='usuarios.users')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
