# Generated by Django 4.1.1 on 2022-09-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_users_telefono_alter_users_telefono_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telefono_work',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
