# Generated by Django 4.1.1 on 2022-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_users_telefono_alter_users_telefono_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
