# Generated by Django 4.1.1 on 2022-10-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sexo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='tipo_cuenta',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Institucional', 'Institucional')], max_length=13),
        ),
    ]
